name: Test, lint and check commit
on:
  push:
    branches: "*"

jobs:
  unit_test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Find bun version
        id: bun_version
        run: |
          echo "BUN_VERSION=$(grep bun .tool-versions | awk '{print $2}')" >> $GITHUB_OUTPUT

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ steps.bun_version.outputs.BUN_VERSION }}

      - name: Install
        run: |-
          bun install --frozen-lockfile

      - name: Test
        run: |-
          bun run build
          bun run test

  lint_and_check:
    name: Lint and check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Find bun version
        id: bun_version
        run: |
          echo "BUN_VERSION=$(grep bun .tool-versions | awk '{print $2}')" >> $GITHUB_OUTPUT

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ steps.bun_version.outputs.BUN_VERSION }}

      - name: Install
        run: |-
          bun install --frozen-lockfile

      - name: Lint and check
        run: |-
          bun run build
          bun run lint
          bun run check
